# Debug infos from github actions
name: Debug informations

on: ["push"]

permissions: read-all

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - env:
          REF: ${{ toJSON(github) }}
        run: echo $REF
