# Debug infos from github actions
name: Debug informations

on: ["push"]

permissions: read-all

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      out1: ${{ steps.step2.outputs.test }}
    steps:
      - env:
          REF: ${{ toJSON(github) }}
        run: echo $REF
      - id: step2
        run: echo "test=HELLO" >> $GITHUB_OUTPUT
      - id: step3
        env: 
          TEST: ${{ steps.step2.outputs.test }}
        run: echo $TEST
  extract_info:
    runs-on: ubuntu-latest
    outputs:
      out1: ${{ steps.curl.outputs.release }}
    env: 
      TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - id: curl
        run: >
          echo release=$(curl -L
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer $TOKEN" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/zckv/pypi_in_pages_example/releases/latest)
          >> $GITHUB_OUTPUT
  display_info:
    runs-on: ubuntu-latest
    needs: [extract_info]
    env: 
      release: ${{ needs.extract_info.outputs.out1 }}
    steps:
      - run: echo $release
  display_assets_only:
    runs-on: ubuntu-latest
    needs: [extract_info]
    strategy:
      matrix:
        VERSION: ${{ fromJSON(needs.extract_info.outputs.out1).assets[*].name }}
        LINK: ${{ fromJSON(needs.extract_info.outputs.out1).assets[*].browser_download_url }}
    env: 
      NAME: example_package
    steps:
      - run: |
          echo NAME = $NAME
          echo VERSION = $VERSION
          echo LINK = $LINK
  
    
