# Debug infos from github actions
name: Debug informations

on: ["push"]

permissions: read-all

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      out1: ${{ steps.step2.outputs.test }}
    steps:
      - env:
          REF: ${{ toJSON(github) }}
        run: echo $REF
      - id: step2
        run: echo "test=HELLO" >> $GITHUB_OUTPUT
      - id: step3
        env: 
          TEST: ${{ steps.step2.outputs.test }}
        run: echo $TEST
  extract_info:
    runs-on: ubuntu-latest
    # Extract from curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer $TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/zckv/pypi_in_pages_example/releases/latest
  display_info:
    runs-on: ubuntu-latest
    
