# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    tags:
      - "v*.*.*"
    
permissions:
  contents: write

# THE PYTHON PACKAGE IS BUILT USING POETRY
# IF YOU WANT TO USE THIS WORKFLOW, CONFIGURE THESE
env:
  # TODO use variable from somewhere to extract package name in kebab case
  PKGNAME: example-package
  REPO_URL: https://api.github.com/repos/zckv/pypi_in_pages_example/actions/workflows/addrepo.yml/dispatches

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ASSETS: ${{ steps.release.outputs.assets }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install poetry environement
        run: |
          cd ${{ env.PKGNAME }}
          python -m pip install poetry
          if [ -f pyproject.toml ]; then poetry install -n; fi
      - name: Build package with poetry
        id: "build"
        run: |
          cd ${{ env.PKGNAME }}
          echo "BUILDING PACKAGE in $(pwd)"
          poetry build
      - name: Release
        id: "release"
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PKGNAME }}/dist/*
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        ASSET: ${{ fromJSON(needs.build.outputs.ASSETS) }}
    env: 
      TOKEN: ${{ secrets.PAT_TOKEN }}
      VERSION: ${{ matrix.ASSET.name }}
      LINK: ${{ matrix.ASSET.browser_download_url }}
    steps:
      - name: Add to pages index
        run: >
          curl -L -X POST -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer $TOKEN"
          -H "X-GitHub-Api-Version: 2022-11-28"
          ${{ env.REPO_URL }}
          -d "{\"ref\":\"master\",\"inputs\":{\"name\": \"$PKGNAME\", \"version\": \"$VERSION\", \"link\": \"$LINK\"}}"
